/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ekgp49.dbc;

import java.io.PrintStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Scanner;

public class ServerApp {
  public static void main(String[] args) throws Exception {
    System.out.println("앱 서버입니다");
    try (ServerSocket serverSocket = new ServerSocket(9999);) {
      while (true) {
        System.out.println("연결 대기중");
        Socket socket = serverSocket.accept();
        processRequest(socket);
      }
    } catch (Exception e) {
      System.out.println("서버 문제 발생");
      e.printStackTrace();
    }
  }

  static void processRequest(Socket socket) {
    try (PrintStream out = new PrintStream(socket.getOutputStream());
        Scanner in = new Scanner(socket.getInputStream());) {

      System.out.println("클라이언트측 메시지: " + in.nextLine());

      String message = "서버예요";
      out.println(message);

      System.out.println("서버: " + message);
      System.out.println("-------------연결 종료---------------");
    } catch (Exception e) {

    }
  }
}

