/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ekgp49.dbc;

import org.junit.Test;

public class ClientAppTest {
  @Test
  public void testAppHasAGreeting() {
    // ClientApp classUnderTest = new ClientApp();
    // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }
}
